# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: interlinkedcorp
# "service" is the name of this project. This will also be added to your AWS resource names.
service: lambda-framework

provider:
  name: aws
  runtime: python3.11

package:
  individually: true  # Each Lambda is packaged separately

functions:
  mvt:
    handler: services/mvt/handler.handler
    package:
      include:
        - services/mvt/**
    events:
      - http:
          path: api/mvt
          method: get

  transcribe:
    handler: services/transcribe/handler.transcribe_task
    package:
      include:
        - services/transcribe/**
    events:
      - http:
          path: api/transcribe
          method: post

  sample:
    handler: services/sample/handler.sum
    events:
      - http:
          path: add
          method: post

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    layer: false