# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: interlinkedcorp
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: lambdas
# "service" is the name of this project. This will also be added to your AWS resource names.
service: lambda-framework

provider:
  name: aws
  runtime: python3.11
  region: us-east-2
  apiGateway:
    binaryMediaTypes:
      - 'application/vnd.mapbox-vector-tile'
      - 'application/octet-stream'
      - 'application/x-protobuf'
      - 'application/zip'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:ListBucket
          Resource: 
            - "arn:aws:s3:::mvt-tile-bucket/*"

package:
  individually: true  # Each Lambda is packaged separately

functions:
  mvt:
    handler: services/mvt/handler.handler
    package:
      include:
        - services/mvt/**
    events:
      - http:
          path: api/mvt
          method: get
          cors: true   
      - http:
          path: api/
          method: get
          cors: true
      - httpApi:
          method: GET
          path: /mvt
    url: true  # Enable Lambda Function URL


  transcribe:
    handler: services/transcribe/handler.transcribe_task
    package:
      include:
        - services/transcribe/**
    events:
      - http:
          path: api/transcribe
          method: post
          cors: true

  sample:
    handler: services/sample/handler.sum
    events:
      - http:
          path: add
          method: post

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    layer: false